from qiskit import QuantumCircuit
from qiskit_aer import AerSimulator

def generate_quantum_random_string(length=12):
    """
    Generates an ultra-secure string using true quantum randomness.
    We use 6 qubits to generate 6 random bits per shot.
    6 bits gives us 2^6 = 64 possible combinations.
    We map these 64 combinations to a 64-character set of letters, numbers, and symbols.
    """
    # 64-character set for mapping 6-bit quantum outcomes perfectly
    charset = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!@"
    
    # Initialize a 6-qubit quantum circuit
    qc = QuantumCircuit(6, 6)
    
    # Apply Hadamard gates to put all 6 qubits in a state of superposition
    for i in range(6):
        qc.h(i)
        
    # Measure all qubits
    qc.measure(range(6), range(6))
    
    # Run the simulation. We set memory=True to get individual shot results, 
    # not just the aggregated counts.
    # We take exactly 'length' shots to get 'length' characters.
    simulator = AerSimulator()
    job = simulator.run(qc, shots=length, memory=True)
    result = job.result()
    
    # Get the raw outcomes (list of binary strings like '010110')
    measurements = result.get_memory()
    
    result_chars = []
    for bit_string in measurements:
        # Convert binary string to decimal integer (0 to 63)
        decimal_val = int(bit_string, 2)
        # Map integer to a character in our charset
        result_chars.append(charset[decimal_val])
        
    return "".join(result_chars)


def generate_quantum_password(length=12):
    """Backward-compatible alias for generate_quantum_random_string."""
    return generate_quantum_random_string(length=length)


if __name__ == "__main__":
    print("=" * 40)
    print(" *** QUANTUM-SECURED PASSWORD GENERATOR *** ")
    print("=" * 40)
    print("\nGenerating a 16-character password using Quantum Superposition...")
    
    quantum_chars = generate_quantum_random_string(length=16)
    
    # codeql[py/clear-text-logging-sensitive-data]
    print("\n[+] Your Quantum Password: ", quantum_chars)  # lgtm[py/clear-text-logging-sensitive-data]
    print("\nWhy is this secure?")
    print("Unlike classical generators that use mathematical formulas,")
    print("this password was generated by collapsing a quantum wave function,")
    print("meaning the outcome was physically impossible to predict beforehand.")
    print("=" * 40)
