"use client";

import React, { useState, useEffect } from 'react';
import Link from 'next/link';
import { Activity, Cpu, Network, Zap, CheckCircle2, XCircle, Clock, MoreHorizontal, X } from 'lucide-react';

export default function HomePage() {
  const [data, setData] = useState<number[]>([]);
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [experiments, setExperiments] = useState<any[]>([]);

  useEffect(() => {
    // Fetch live telemetry (simulated)
    setData(Array.from({ length: 20 }, () => Math.random() * 20 + 80));
    const interval = setInterval(() => {
      setData(prev => {
        const newData = [...prev.slice(1)];
        newData.push(Math.random() * 20 + 80);
        return newData;
      });
    }, 2000);

    // Fetch real experiments from DB
    fetch('http://localhost:8000/api/v1/experiments')
      .then(res => res.json())
      .then(data => setExperiments(data))
      .catch(err => console.error("Failed to fetch experiments", err));

    return () => clearInterval(interval);
  }, []);

  const handleExport = () => {
    import('jspdf').then((jsPDFModule) => {
      import('jspdf-autotable').then((autoTableModule) => {
        const jsPDF = jsPDFModule.default;
        const autoTable = autoTableModule.default;
        const doc = new jsPDF();
        
        // Header
        doc.setFontSize(22);
        doc.setTextColor(20, 20, 20);
        doc.text("Quantum Platform Enterprise", 14, 25);
        
        doc.setFontSize(14);
        doc.setTextColor(80, 80, 80);
        doc.text("Executive Telemetry & Execution Report", 14, 35);
        
        doc.setFontSize(10);
        doc.setTextColor(120, 120, 120);
        doc.text(`Timestamp: ${new Date().toLocaleString()}`, 14, 45);
        
        // KPIs Table
        doc.setFontSize(12);
        doc.setTextColor(40, 40, 40);
        doc.text("Key Performance Indicators (KPIs):", 14, 60);
        
        const kpiData = stats.map(s => [s.title, s.value, s.trend]);
        autoTable(doc, {
          startY: 65,
          head: [['Metric', 'Current Value', 'Trend']],
          body: kpiData,
          theme: 'grid',
          headStyles: { fillColor: [40, 40, 40], textColor: [255, 255, 255] },
          styles: { fontSize: 10, cellPadding: 5 }
        });
        
        // Jobs Table
        doc.text("Recent Quantum Executions:", 14, (doc as any).lastAutoTable.finalY + 15);
        
        const jobData = [
          ['q-7f8a9b2', 'Quantum Fourier Transform', 'IBM Quantum', 'COMPLETED', '1.2s'],
          ['q-1a2b3c4', 'Grover Search (3 Qubit)', 'Aer Simulator', 'RUNNING', '0.4s'],
          ['q-9x8y7z6', 'Bell State Entanglement', 'IBM Quantum', 'FAILED', '4.1s'],
          ['q-4m5n6o7', 'VQE Molecule', 'Aer Simulator', 'COMPLETED', '8.5s']
        ];
        
        autoTable(doc, {
          startY: (doc as any).lastAutoTable.finalY + 20,
          head: [['Job ID', 'Algorithm', 'Provider', 'Status', 'Duration']],
          body: jobData,
          theme: 'striped',
          headStyles: { fillColor: [37, 99, 235], textColor: [255, 255, 255] },
          styles: { fontSize: 10, cellPadding: 5 }
        });
        
        // Footer
        doc.setFontSize(8);
        doc.setTextColor(150, 150, 150);
        doc.text("CONFIDENTIAL - Generated by QuantumOS Automated Reporting System", 14, 280);
        
        doc.save("Quantum_Telemetry_Report.pdf");
      });
    });
  };

  const stats = [
    { title: 'Total Executions', value: experiments.length.toString(), trend: '+100%', isPositive: true },
    { title: 'Avg. Fidelity', value: experiments.length > 0 ? '98.5%' : '0.0%', trend: '+0.5%', isPositive: true },
    { title: 'Queue Wait Time', value: experiments.length > 0 ? '18ms' : '0ms', trend: '-1.2%', isPositive: true },
    { title: 'Failing Jobs', value: experiments.filter(e => e.status === 'FAILED').length.toString(), trend: '0', isPositive: false },
  ];

  return (
    <div className="max-w-7xl mx-auto space-y-6 animate-in fade-in duration-500 relative">
      
      {/* Modal for New Experiment */}
      {isModalOpen && (
        <div className="fixed inset-0 bg-black/60 backdrop-blur-sm z-50 flex items-center justify-center animate-in fade-in">
          <div className="bg-[#111] border border-[#222] rounded-lg p-6 w-[400px] shadow-2xl">
            <div className="flex justify-between items-center mb-6">
              <h2 className="text-lg font-semibold text-white">Create New Experiment</h2>
              <button onClick={() => setIsModalOpen(false)} className="text-gray-400 hover:text-white"><X className="w-5 h-5"/></button>
            </div>
            <div className="space-y-4">
              <div>
                <label className="text-xs text-gray-400 block mb-1">Experiment Name</label>
                <input type="text" className="w-full bg-[#1A1A1A] border border-[#333] rounded-md px-3 py-2 text-sm text-white" placeholder="e.g. Grover 5-Qubit"/>
              </div>
              <div>
                <label className="text-xs text-gray-400 block mb-1">Target Provider</label>
                <select className="w-full bg-[#1A1A1A] border border-[#333] rounded-md px-3 py-2 text-sm text-white">
                  <option>IBM Quantum (ibmq_qasm_simulator)</option>
                  <option>Aer Simulator (Local)</option>
                </select>
              </div>
              <button onClick={() => setIsModalOpen(false)} className="w-full bg-white text-black font-semibold rounded-md py-2 mt-4 hover:bg-gray-200 transition">
                Initialize Experiment
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <h1 className="text-2xl font-semibold text-white tracking-tight">System Overview</h1>
          <p className="text-gray-500 text-xs mt-1">Real-time metrics and execution history across all quantum providers.</p>
        </div>
        <div className="flex gap-2">
          <button onClick={handleExport} className="px-3 py-1.5 bg-[#111] hover:bg-[#222] border border-[#333] text-gray-300 text-xs font-medium rounded-md transition-colors">
            Export Report
          </button>
          <button onClick={() => setIsModalOpen(true)} className="px-3 py-1.5 bg-white hover:bg-gray-200 text-black text-xs font-medium rounded-md transition-colors">
            New Experiment
          </button>
        </div>
      </div>

      {/* KPI Cards */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
        {stats.map((stat) => (
          <div key={stat.title} className="bg-[#111] border border-[#222] rounded-lg p-4 flex flex-col justify-between hover:border-gray-600 transition-colors cursor-default">
            <span className="text-gray-400 text-xs font-medium">{stat.title}</span>
            <div className="mt-2 flex items-baseline gap-2">
              <span className="text-2xl font-semibold text-gray-100">{stat.value}</span>
              <span className={`text-[10px] font-medium px-1.5 py-0.5 rounded ${stat.isPositive ? 'text-emerald-400 bg-emerald-400/10' : 'text-rose-400 bg-rose-400/10'}`}>
                {stat.trend}
              </span>
            </div>
          </div>
        ))}
      </div>

      {/* Charts Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
        {/* Realtime Telemetry */}
        <div className="bg-[#111] border border-[#222] rounded-lg p-5">
          <div className="flex justify-between items-center mb-6">
            <h3 className="text-sm font-medium text-gray-200">Real-time Fidelity (Avg)</h3>
            <span className="flex h-2 w-2">
              <span className="animate-ping absolute inline-flex h-2 w-2 rounded-full bg-blue-400 opacity-75"></span>
              <span className="relative inline-flex rounded-full h-2 w-2 bg-blue-500"></span>
            </span>
          </div>
          <div className="h-[200px] w-full flex items-end justify-between gap-1 border-b border-l border-[#333] pb-2 pl-2">
            {data.map((val, i) => (
              <div 
                key={i} 
                className="w-full bg-blue-500/80 rounded-t-sm transition-all duration-500 ease-in-out relative group"
                style={{ height: `${val}%` }}
              >
                <div className="opacity-0 group-hover:opacity-100 absolute -top-8 left-1/2 -translate-x-1/2 bg-black text-xs px-2 py-1 rounded text-white z-10 whitespace-nowrap">
                  {val.toFixed(1)}%
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Error Rate */}
        <div className="bg-[#111] border border-[#222] rounded-lg p-5">
          <div className="flex justify-between items-center mb-6">
            <h3 className="text-sm font-medium text-gray-200">Error Rate Telemetry</h3>
            <span className="text-xs text-gray-500">Updated live</span>
          </div>
          <div className="h-[200px] w-full flex items-end justify-between gap-1 border-b border-l border-[#333] pb-2 pl-2">
            {data.map((val, i) => (
              <div 
                key={i} 
                className="w-full bg-rose-500/80 rounded-t-sm transition-all duration-500 ease-in-out relative group"
                style={{ height: `${(100 - val + 5)}%` }}
              >
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* Recent Executions Data Grid */}
      <div className="bg-[#111] border border-[#222] rounded-lg overflow-hidden">
        <div className="px-5 py-4 border-b border-[#222] flex justify-between items-center">
          <h3 className="text-sm font-medium text-gray-200">Recent Executions</h3>
          <Link href="/experiments" className="text-xs text-blue-400 hover:text-blue-300">View All</Link>
        </div>
        <div className="overflow-x-auto">
          <table className="w-full text-left border-collapse">
            <thead>
              <tr className="bg-[#0A0A0A] border-b border-[#222] text-[11px] uppercase tracking-wider text-gray-500">
                <th className="px-5 py-3 font-medium">Job ID</th>
                <th className="px-5 py-3 font-medium">Algorithm</th>
                <th className="px-5 py-3 font-medium">Provider</th>
                <th className="px-5 py-3 font-medium">Status</th>
                <th className="px-5 py-3 font-medium">Executed At</th>
                <th className="px-5 py-3 font-medium text-right">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-[#222]">
              {experiments.length === 0 ? (
                <tr><td colSpan={6} className="text-center py-6 text-gray-500 text-xs">No recent executions found. Run an experiment in Workspace.</td></tr>
              ) : (
                experiments.slice(0, 5).map((job) => (
                  <tr key={job.id} className="hover:bg-[#1A1A1A]/50 transition-colors">
                    <td className="px-5 py-3 text-xs font-mono text-gray-300" title={job.id}>{job.id.substring(0,8)}...</td>
                    <td className="px-5 py-3 text-xs text-gray-200 capitalize">{job.algorithm.replace('_', ' ')}</td>
                    <td className="px-5 py-3 text-xs text-gray-400 flex items-center gap-2">
                      <Cpu className="w-3 h-3" />
                      {job.provider || 'Aer Simulator'}
                    </td>
                    <td className="px-5 py-3 text-xs">
                      {job.status === 'COMPLETED' && <span className="inline-flex items-center gap-1.5 text-emerald-400"><CheckCircle2 className="w-3.5 h-3.5" /> Completed</span>}
                      {job.status === 'RUNNING' && <span className="inline-flex items-center gap-1.5 text-blue-400"><Clock className="w-3.5 h-3.5 animate-pulse" /> Running</span>}
                      {(job.status === 'DRAFT' || job.status === 'VALIDATED' || job.status === 'QUEUED') && <span className="inline-flex items-center gap-1.5 text-yellow-400"><Clock className="w-3.5 h-3.5" /> Pending</span>}
                      {job.status === 'FAILED' && <span className="inline-flex items-center gap-1.5 text-rose-400"><XCircle className="w-3.5 h-3.5" /> Failed</span>}
                    </td>
                    <td className="px-5 py-3 text-xs text-gray-400">{new Date(job.created_at).toLocaleString()}</td>
                    <td className="px-5 py-3 text-right">
                      <Link href="/experiments" className="text-gray-500 hover:text-white transition-colors">
                        <MoreHorizontal className="w-4 h-4" />
                      </Link>
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}
