"""SecurityAnalytics implementation for key rate and QBER checks.

References:
    Docs/QBER_SPEC.md §1-§5
    Docs/07_SYSTEM_ARCHITECTURE.md §5
"""

from typing import Optional


class SecurityAnalytics:
    """Computes quantum security metrics over sifted simulation results.

    Provides functions for analyzing QBER, key rates, and statistical
    confidence intervals for eavesdropper detection.
    """

    @staticmethod
    def compute_qber(
        alice_bits: list[int], bob_bits: list[int], sample_indices: list[int]
    ) -> Optional[float]:
        """Compute the Quantum Bit Error Rate from a compared public sample.

        Args:
            alice_bits: List of original bits generated by Alice.
            bob_bits: List of measured bits obtained by Bob.
            sample_indices: Index set chosen publicly for comparison.

        Returns:
            The error rate as a float, or None if the sample index set is empty.
        """
        if not sample_indices:
            return None

        errors = 0
        for idx in sample_indices:
            if idx < len(alice_bits) and idx < len(bob_bits):
                if alice_bits[idx] != bob_bits[idx]:
                    errors += 1
        return errors / len(sample_indices)

    @staticmethod
    def compute_key_rate(final_key_length: int, n_qubits: int) -> float:
        """Calculate the resulting ratio of key length to total qubits.

        Args:
            final_key_length: Length of final secret key.
            n_qubits: Total raw qubits simulated.

        Returns:
            The key rate as a float.
        """
        return final_key_length / n_qubits if n_qubits > 0 else 0.0

    @staticmethod
    def detection_probability(
        qber: float, sample_size: int, noise_floor: float = 0.0
    ) -> float:
        """Estimate the statistical confidence that eavesdropping is present.

        Args:
            qber: Observed Quantum Bit Error Rate.
            sample_size: The number of compared bits in the estimation.
            noise_floor: Expected natural background noise level.

        Returns:
            Statistical confidence (0.0 to 1.0) of eavesdropper presence.
        """
        if qber <= noise_floor or sample_size <= 0:
            return 0.0
        p_no_detect = (1.0 - (qber - noise_floor)) ** sample_size
        return max(0.0, min(1.0, 1.0 - p_no_detect))
