"""QBER (Quantum Bit Error Rate) Service implementation.

References:
    Docs/QBER_SPEC.md §3, §4
"""

from typing import Sequence

from qst.core.bb84.validators import validate_bb84_bits
from qst.exceptions.validation import ValidationError
from qst.models.results import QBERResult


class QBERService:
    """Computes the Quantum Bit Error Rate (QBER) by comparing sifted keys."""

    def calculate_qber(
        self, alice_sifted: Sequence[int], bob_sifted: Sequence[int]
    ) -> QBERResult:
        """Calculate QBER between Alice and Bob's sifted keys.

        Args:
            alice_sifted: Sifted key bits generated by Alice.
            bob_sifted: Sifted key bits measured by Bob.

        Returns:
            A QBERResult containing error count, compared length, QBER, and notes.

        Raises:
            ValidationError: If sifted keys are invalid or have mismatched lengths.
        """
        validate_bb84_bits(alice_sifted)
        validate_bb84_bits(bob_sifted)

        if len(alice_sifted) != len(bob_sifted):
            raise ValidationError(
                f"Alice sifted key length ({len(alice_sifted)}) does not match "
                f"Bob sifted key length ({len(bob_sifted)}).",
                code="QST-VAL-805",
            )

        sifted_key_length = len(alice_sifted)

        if sifted_key_length == 0:
            return QBERResult(
                error_count=0,
                sifted_key_length=0,
                qber=0.0,
                confidence_notes="Warning: Sifted key length is 0. QBER cannot be estimated accurately. Confidence is low.",
            )

        error_count = sum(1 for a, b in zip(alice_sifted, bob_sifted) if a != b)
        qber = float(error_count / sifted_key_length)

        if sifted_key_length < 10:
            confidence_notes = "Warning: Sifted key length is short. QBER estimate has high statistical variance."
        else:
            confidence_notes = (
                "Normal: Adequate key length for reliable QBER estimation."
            )

        return QBERResult(
            error_count=error_count,
            sifted_key_length=sifted_key_length,
            qber=qber,
            confidence_notes=confidence_notes,
        )
